# API-запросs

@baseUrl = http://127.0.0.1:8000/api/v1/courses

# получение курса по id
GET {{baseUrl}}/2/
Content-Type: application/json

###

# получение курса по фильтру по id
GET {{baseUrl}}/?id=2
Content-Type: application/json

###

# получение списка курсов
GET {{baseUrl}}/
Content-Type: application/json

###

# создание нового курса
POST {{baseUrl}}/
Content-Type: application/json

{
  "name": "Основы алгебры",
  "students": [
    1,
    2
    ]
}
###

# обновление курса
PATCH {{baseUrl}}/4/
Content-Type: application/json

{
  "name": "Основы мат.анализа-2"
}
###

# удаление курса
DELETE {{baseUrl}}/4/
Content-Type: application/json
